
################################################################################################################################
#  Strimzi Kafka cluster Deploy                                                                                                              
#    - It is responsible to deploy the Kafka Cluster into kubernetes                                                                                               #
################################################################################################################################
---
- name: Setting namespaces and Deploying Kafka Cluster 
  hosts: localhost
  vars_files:
    - ../../config_vars/global_vars.yaml

  tasks:

    ###################################################################################################################################
    #  Modify File - kafka-ephemeral.yaml                                                                      
    #    - It will modify the file to add the namespace sent as parameter
    ####################################################################################################################################
    - name: Setting kafka cluster namespace -> {{ kafka_cluster_namespace_var }} to ../{{strimzi_kafka_cluster_dir}}/kafka-ephemeral.yaml
      shell: |
        sed -i '' "s/replace/{{ kafka_cluster_namespace_var }}/g" ../{{strimzi_kafka_cluster_dir}}/kafka-ephemeral.yaml
        exit 0
      when: kafka_cluster_namespace_var is defined and ansible_system == 'Darwin'

    ###################################################################################################################################
    #  Deploy File - kafka-ephemeral.yaml                                                                      
    #    - It will deploy the file under namespace sent in the parameter
    #    - Wait the kafka cluster deployment
    #    - Verify if the Kafka Cluster was successfully deployed.
    ####################################################################################################################################
    - name: Deploying the Kafka Cluster ../{{strimzi_kafka_cluster_dir}}/kafka-ephemeral.yaml for namespace -> {{ kafka_cluster_namespace_var }}
      shell: |
        kubectl apply -f  ../{{strimzi_kafka_cluster_dir}}/kafka-ephemeral.yaml -n  {{ kafka_cluster_namespace_var }}
      when: kafka_cluster_namespace_var is defined
      register: deploy_kafka_results
    - debug:
        var: deploy_kafka_results.stdout_lines

   # - name: Waiting kafka cluster deployment
   #   shell: |
   #     kubectl wait kafka/{{ kafka_cluster_namespace_var }}-kafka-cluster --for=condition=Ready --timeout=300s -n {{ kafka_cluster_namespace_var }}
   #   register: results
  #  - debug:
   #     var: results.stdout_lines

    - name: Verifying if the Kafka Cluster was successfully deployed
      shell: |
        kubectl get deployments -n  {{ kafka_cluster_namespace_var }}
      when: kafka_cluster_namespace_var is defined
      register: check_deployments_results
    - debug:
        var: check_deployments_results.stdout_lines
    
    ###################################################################################################################################
    # Modify kafka-ephemeral.yaml                                                                    
    #    - It is reverting the namespace of file to be ready for the next deployment
    ####################################################################################################################################
    - name: Reverting the changes added to namespace {{kafka_cluster_namespace_var }} in ../{{strimzi_kafka_cluster_dir}}/kafka-ephemeral.yaml
      shell: |
        sed -i '' "s/{{ kafka_cluster_namespace_var }}/replace/g" ../{{strimzi_kafka_cluster_dir}}/kafka-ephemeral.yaml
        exit 0
      when: kafka_cluster_namespace_var is defined and ansible_system == 'Darwin'
    
    ###################################################################################################################################
    # Kafka Topics
    #   - This section is responsible to modify the namespace for the kafka_topics files 
    #   - Create Kafka topics
    #
    ###################################################################################################################################
    - name: Setting namespace {{kafka_cluster_namespace_var}} for ../{{kafka_topics_dir}}/*.yaml
      shell: |
        sed -i '' "s/replace/{{ kafka_cluster_namespace_var }}/g" ../{{kafka_topics_dir}}/*.yaml
        exit 0
      when: ansible_system == 'Darwin'

    - name: Creating Kafka topics from ../{{kafka_topics_dir}} to namespace {{ kafka_cluster_namespace_var }}
      shell: |
        kubectl apply -f  ../{{kafka_topics_dir}} -n {{ kafka_cluster_namespace_var }}
      register: kfk_topic_results
    - debug:
        var: kfk_topic_results.stdout_lines

    - name: Verifying if the Kafka Topic was successfully deployed
      shell: |
        kubectl get kafkatopic -n {{ kafka_cluster_namespace_var }}
      register: check_topic_results
    - debug:
        var: check_topic_results.stdout_lines
    
    - name: Reverting changes of ../{{strimzi_kafka_cluster_dir}}/*.yaml to next kafka deployment
      shell: |
        sed -i '' "s/{{ kafka_cluster_namespace_var }}/replace/g" ../{{strimzi_kafka_cluster_dir}}/*.yaml
        exit 0
      when: ansible_system == 'Darwin'

    - name: Reverting changes of ../{{kafka_topics_dir}}/*.yaml to next topic creation 
      shell: |
        sed -i '' "s/{{ kafka_cluster_namespace_var }}/replace/g" ../{{kafka_topics_dir}}/*.yaml
        exit 0
      when: ansible_system == 'Darwin'

    